#include <avr/pgmspace.h>

const char index_html[] PROGMEM =
{

"<!doctype html><html lang=\"en\"> <head> <meta charset=\"utf-8\"> <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\"> <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\"> <link rel=\"stylesheet\" href=\"css/station.css\"> <link rel=\"stylesheet\" href=\"//cdn.materialdesignicons.com/4.5.95/css/materialdesignicons.min.css\"> <title>Weather Station | Dashboard</title> </head> <body> %NAVBAR% <div class=\"container-fluid\" style=\"margin-top:80px\"> <h3 id=\"dashboardTitle\">Dashboard - not connected</h3> <table class=\"table\" style=\"background-color: white\"> <thead class=\"thead-light\"> <tr> <th>Sensor readings</th> </tr></thead> <tbody> <tr> <td> <ul id=\"sensorReadingsList\" class=\"list-group\"> <li class=\"list-group-item\">Waiting...</li></ul> </td></tr></tbody> </table> <table class=\"table\" style=\"background-color: white\"> <thead class=\"thead-light\"> <tr> <th>Internet current weather</th> </tr></thead> <tbody> <tr> <td> <ul id=\"internetWeatherList\" class=\"list-group\"> <li class=\"list-group-item\">Waiting...</li></ul> </td></tr></tbody> </table> <table class=\"table\" style=\"background-color: white\"> <thead class=\"thead-light\"> <tr> <th>Internet weather forecast</th> </tr></thead> <tbody> <tr> <td> <ul id=\"internetForecastList\" class=\"list-group\"> <li class=\"list-group-item\">Waiting...</li></ul> </td></tr></tbody> </table> </div><script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script> <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script> <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script> <script src=\"js/station.js\"></script> </body></html>"

};

const char station_js[] PROGMEM =
{

"var websocket;\n"
"\n"
"function init()\n"
"{   \n"
"    openWebSocket();\n"
"}\n"
"\n"
"function updateSensorReadings(messageData)\n"
"{\n"
"    var readings = messageData.readings;   \n"
"    var currentValue;\n"
"   \n"
"    $(\"#sensorReadingsList\").empty();\n"
"\n"
"    if(readings.metric)\n"
"    {\n"
"        currentValue = readings.temp.toFixed(1) + \"&#8451\";\n"
"    }\n"
"    else\n"
"    {\n"
"        var farenheit = (readings.temp * 1.8) + 32;\n"
"        currentValue = farenheit.toFixed(1) + \"&#8457\";\n"
"    }\n"
"    $(\"#sensorReadingsList\").append('<li class=\"list-group-item mdi mdi-thermometer\">' + 'Temperature: ' + currentValue + '</li>');\n"
"    \n"
"    currentValue = readings.humidity.toFixed(1) + \"%\";\n"
"    $(\"#sensorReadingsList\").append('<li class=\"list-group-item mdi mdi-water-percent\">' + 'Humidity: ' + currentValue + '</li>');\n"
"\n"
"    if(readings.metric)\n"
"    {\n"
"        currentValue = readings.pressure.toFixed(1) + \" hPA\";\n"
"    }\n"
"    else\n"
"    {\n"
"        currentValue = readings.pressure.toFixed(1) + \" mb\";\n"
"    }\n"
"    $(\"#sensorReadingsList\").append('<li class=\"list-group-item mdi mdi-gauge\">' + 'Pressure: ' + currentValue + '</li>');\n"
"}\n"
"\n"
"function updateInternetCurrent(messageData)\n"
"{\n"
"    var current = messageData.currentReadings;\n"
"    var currentValue;\n"
"    var observedTime;\n"
"   \n"
"    $(\"#internetWeatherList\").empty();\n"
"\n"
"    if(current.metric)\n"
"    {\n"
"        currentValue = current.temp.toFixed(1) + \"C - \" + current.description;\n"
"    }\n"
"    else\n"
"    {\n"
"        currentValue = current.temp.toFixed(1) + \"F - \" + current.description;\n"
"    }\n"
"    $(\"#internetWeatherList\").append('<li class=\"list-group-item\">' + currentValue + '</li>');\n"
"    \n"
"    currentValue = \"Humidity: \" + current.humidity + \"%\";\n"
"    $(\"#internetWeatherList\").append('<li class=\"list-group-item\">' + currentValue + '</li>');\n"
"    \n"
"    currentValue = \"Wind speed: \" + current.windSpeed + \"m/s from \" + current.windDirection + \"&#176\";\n"
"    $(\"#internetWeatherList\").append('<li class=\"list-group-item\">' + currentValue + '</li>');\n"
"\n"
"    observedTime = new Date(current.time * 1000);\n"
"    currentValue = \"Observed at: \" + observedTime.toLocaleTimeString(\"en-GB\") + \" on \" + observedTime.toLocaleDateString(\"en-GB\");\n"
"    $(\"#internetWeatherList\").append('<li class=\"list-group-item\">' + currentValue + '</li>');\n"
"}\n"
"\n"
"function updateWeatherForecast(messageData)\n"
"{\n"
"    var list = messageData.list;\n"
"    var currentValue;\n"
"    var forecastTime;\n"
"    var dateString;\n"
"    var days = [\"Sunday\", \"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\", \"Saturday\"];\n"
"\n"
"    $(\"#internetForecastList\").empty();\n"
"\n"
"    for(day of list)\n"
"    {\n"
"        forecastTime = new Date(day.time * 1000);\n"
"        dateString = days[forecastTime.getDay()];\n"
"    \n"
"        if(messageData.metric)\n"
"        {\n"
"            currentValue = dateString + \" - \" + day.description + \", min \" + day.tempMin.toFixed(1) + \"C, max \" + day.tempMax.toFixed(1) + \"C\";\n"
"        }\n"
"        else\n"
"        {\n"
"            currentValue = dateString + \" - \" + day.description + \", min \" + day.tempMin.toFixed(1) + \"F, max \" + day.tempMax.toFixed(1) + \"F\";\n"
"        }\n"
"            \n"
"        $(\"#internetForecastList\").append('<li class=\"list-group-item\">' + currentValue + '</li>');\n"
"    }\n"
"\n"
"}\n"
"\n"
"function openWebSocket() \n"
"{\n"
"    websocket = new WebSocket('ws://' + document.location.host + '/ws');\n"
"    websocket.onopen = function(evt) { onOpen(evt) };\n"
"    websocket.onclose = function(evt) { onClose(evt) };\n"
"    websocket.onmessage = function(evt) { onMessage(evt) };\n"
"    websocket.onerror = function(evt) { onError(evt) };\n"
"}\n"
"\n"
"function onOpen(evt)\n"
"{    \n"
"    $(\"#dashboardTitle\").html(\"Dashboard - connected\");\n"
"}\n"
"\n"
"function onClose(evt)\n"
"{\n"
"    $(\"#dashboardTitle\").html(\"Dashboard - not connected\");\n"
"}\n"
"\n"
"function onMessage(evt)\n"
"{\n"
"    console.log(evt.data);\n"
"\n"
"    var messageData = JSON.parse(evt.data);\n"
"\n"
"    switch(messageData.type)\n"
"    {\n"
"        case \"sensorReadings\":\n"
"            updateSensorReadings(messageData);\n"
"            break;\n"
"        case \"currentWeather\":\n"
"            updateInternetCurrent(messageData);\n"
"            break;\n"
"        case \"weatherForecast\":\n"
"            updateWeatherForecast(messageData);\n"
"            break;\n"
"    }\n"
"\n"
"}\n"
"\n"
"function onError(evt)\n"
"{\n"
"}\n"
"\n"
"function doSend(message)\n"
"{\n"
"    websocket.send(message);\n"
"}\n"
"\n"
"window.addEventListener(\"load\", init, false);\n"
""

};